### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by Water-Moon** [ikexing-cn/RandomTweaker#51]
A typo in [this](https://github.com/ikexing-cn/RandomTweaker/blob/969afa769d49277d6755775aa2a6ecc65bf62d8f/src/main/java/ink/ikx/rt/Main.java#L57) line ("Se**r**ver" -> "Sever") means the mod will crash every time it is constructed server side.

Crash: `net.minecraftforge.fml.common.LoaderException: java.lang.ClassNotFoundException: ink.ikx.rt.impl.internal.proxy.SeverProxy`

**Comment by ikexing-cn** [comment]
this is a really big error....
fixed the next version be will...

**Comment by ikexing-cn** [comment]
讲真，服务器方面的处理我们确实没有仔细检查过，大部分都是理论上感觉没问题了，runserver能跑了，然后就过了。。
最近还在考虑将这一块内容隔离开来，因为crt和mixin的兼容问题打算将其分为两个模组(打包成一个)，但是因为对gradle不太熟悉推进缓慢..

**Comment by Water-Moon** [comment]
另外关于您的Issue里面星辉祭坛那个东西的问题，我倒是有一些想法，一会我整理一下思路之后在那个Issue里面跟您讲

**Comment by ikexing-cn** [comment]
好耶，感谢！（跪

**Comment by ikexing-cn** [comment]
其实可以考虑在Render的最外层上父类考虑`@SideOnly`的注解，这样也可以解决问题吧

**Comment by Water-Moon** [comment]
SideOnly 只能保证一个方法不被加载，但是它的所有import还是被import一遍……所以只注解方法没什么效果
如果把整个JEISlot的类都注解为SideOnly(Client)的话，就会出现另一个问题 - 在服务端加载CrT脚本出现红字（因为CrT的这些方法也被注解成了客户端）

**Comment by Water-Moon** [comment]
``
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from RandomTweaker (randomtweaker)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/Minecraft
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.getDeclaredMethods(Class.java:1975)
	at crafttweaker.CraftTweakerAPI.registerClass(CraftTweakerAPI.java:282)
	at ink.ikx.rt.impl.mods.crafttweaker.CraftTweakerExtension.registerAllClass(CraftTweakerExtension.java:149)
	at ink.ikx.rt.Main.onConstruct(Main.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.loadMods(ModMixinLoader.java:595)
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:98)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:333)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.Minecraft
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 41 more

```

**Comment by Water-Moon** [comment]
它不是JEI的Render执行到，我觉得他是因为您那种registerClass的方式……那个registerClass的确是在构建阶段执行的，然后因为是传递的.class所以会导致所有import都被调用一遍，因此在这种情况下`import net.minecraft.client.Minecraft`就炸了

**Comment by Water-Moon** [comment]
PR发了，#52，您看下

**Comment by ikexing-cn** [comment]
hmm，我好像明白了。
[这里](https://github.com/ikexing-cn/RandomTweaker/blob/969afa769d49277d6755775aa2a6ecc65bf62d8f/src/main/java/ink/ikx/rt/api/mods/jei/slots/IJeiSlot.java)， 没有进行@SideOnly的处理（IJeiElement处理了）。
应该是在CraftTweakerAPI.registerClass(clazz);解析方法的时候，将现有存在的方法都处理了的原因

**Comment by ikexing-cn** [comment]
好，麻烦了，commit你那边手动Close #51吧

**Comment by Water-Moon** [comment]
啊，已经Commit上去了，没写Close #51，危……那我还是在这里手动关闭一下吧（）

**Comment by Water-Moon** [comment]
啊这，那就魔改群见了
抱歉今天耽误了您这么长时间，我其实编程这方面也是个萌新，以后还请大佬多多关照了（危）
